### ISSUE TITLE
Feature Request - Kerberos support for SMBPasswd.py

### ISSUE THREAD

**Issue by mubix** [fortra/impacket#1156]
It would be very awesome to support kerberos (if possible) for password changes.

**Comment by mubix** [comment]
I tried this in `smbclient.py` and got STATUS_WRONG_PASSWORD even though, as you can see I logged in just fine.
```
# ./smbclient.py -k -no-pass bob@dc1.sittingduck.info
Impacket v0.9.24.dev1+20210906.175840.50c76958 - Copyright 2021 SecureAuth Corporation

Type help for list of commands
# password
New Password:
[-] SAMR SessionError: code: 0xc000006a - STATUS_WRONG_PASSWORD - When trying to update a password, this return status indicates that the value provided as the current password is not correct
```

**Comment by mpgn** [comment]
I see cme I press thumb up

**Comment by mubix** [comment]
If you use changepw instead of  `SamrUnicodeChangePasswordUser2` you can set the password without the need of the old password when you have a valid kerberos ticket - see here: 
- https://github.com/GhostPack/Rubeus#changepw
- and the detailed blogpost about it: https://www.harmj0y.net/blog/redteaming/rubeus-now-with-more-kekeo/ by @harmj0y

I realize this would fall outside of the "smb" part of smbpasswd.py so it might be worth a kpasswd.py ? but personally it would be more convenient in my opinion to have it in a single example script.

**Comment by Alef-Burzmali** [comment]
You may be interested in #1189.
I have preferred to create a new script (kpasswd) because the two protocols and implementations are very different.

**Comment by gabrielg5** [comment]
Merged in master @ https://github.com/fortra/impacket/pull/1559
