### ISSUE TITLE
No module named 'impacket.examples.utils  | GetUserSPNs.py File

### ISSUE THREAD

**Issue by yeti-code** [fortra/impacket#1180]
### Configuration  
impacket version:  0.9.23
Python version:  3.9.7
Target OS:  Windows 10

### Debug Output With Command String  
┌──(root💀kali)-[/home/…/Desktop/pnetests/impacket-0.9.23/examples]
└─# python3 /home/kali/Desktop/pnetests/impacket-0.9.23/examples/GetUserSPNs.py controller.local/Machine1:Password1 -dc-ip 10.10.213.98 -request
Traceback (most recent call last):
  File "/home/kali/Desktop/pnetests/impacket-0.9.23/examples/GetUserSPNs.py", line 43, in <module>
    from impacket.examples.utils import parse_credentials
ModuleNotFoundError: No module named 'impacket.examples.utils'

### Additional context  
Space for additional context, investigative results, suspected issue.

Yes, installed all the requirements using pip3, and yes I'm using the latest version.

Also, I have already the issue ticket related to May of this year, where another user had the same issue but with a different script.

I'm on a fully upgraded Kali linux machine btw.

**Comment by tufanturhan** [comment]
thank you p0dalirius !!
