### ISSUE TITLE
No winrmexec.py?

### ISSUE THREAD

**Issue by CaledoniaProject** [fortra/impacket#1403]
I'm looking for a equivalent of https://github.com/Porchetta-Industries/CrackMapExec/blob/master/cme/protocols/winrm.py
Is there anything similar in impacket examples?

I found psexec/dcomexec/..., but no winrm tool.

**Comment by smokeintheshell** [comment]
There are no tools in the Impacket suite of examples to target WinRM. Your best bet for using WinRM is to either use PowerShell on Linux directly (https://github.com/PowerShell/PowerShell) or Evil-WinRM (https://github.com/Hackplayers/evil-winrm)
Evil-WinRM should work for just about any use case you'd have as it supports pass-the-hash, Kerberos tickets, remote script loading, and other advanced features.

**Comment by 0xdeaddood** [comment]
Thanks @smokeintheshell for the comment. 

We re open for PRs if somebody is willing to implement it! Closing
