### ISSUE TITLE
TypeError in set_bytes_from_string  from ImpactPacket.py

### ISSUE THREAD

**Issue by W0nIE** [fortra/impacket#1406]
### Configuration  
impacket version:  0.10.0
Python version:  3.9
Target OS:  Debian (arm)

### Debug Output With Command String  
$ sudo python3 nmapAnswerMachine.py -i eth0 -p 127.0.0.1 -f 'Sun Solaris 9 (SPARC)' -d /nmap-os-db  
```
impacket/impacket/ImpactPacket.py", line 74, in set_bytes_from_string
    self.__bytes = array.array('B', data)
TypeError: cannot use a str to initialize an array with typecode 'B'
```

### PCAP  
Not applicable

### Additional context  
I'm also added a uncrc32 file for run the nmapAnswerMachine.py (this maybe linked to https://github.com/SecureAuthCorp/impacket/issues/403)

**Comment by W0nIE** [comment]
#1407

**Comment by anadrianmanrique** [comment]
closing this as nmapAnswerMachine.py is deprecated
