### ISSUE TITLE
Impacket "GetNPUsers.py"

### ISSUE THREAD

**Issue by Clickobat** [fortra/impacket#1418]
Hello! I'm trying to run "GetNPUsers.py" with python3 GetNPUsers.py and it is displaying this error:

Traceback (most recent call last):
  File "/opt/impacket/examples/./GetNPUsers.py", line 42, in <module>
    from impacket.examples.utils import parse_credentials
ModuleNotFoundError: No module named 'impacket.examples.utils

I believe it is trying to import the impacket.examples.utils module but apparently it was not found.

I've ran pip3 to install all the requirements and i've ran python3 setup.py install to install the modules and stuff.

Also, i am running python 3.10.6 and my OS is Ubuntu, 

Thanks.

**Comment by 0xdeaddood** [comment]
Hi @Clickobat!

That error means you have something wrong in your setup environment. Please check this: https://github.com/fortra/impacket/issues/1180#issuecomment-938662574
