### ISSUE TITLE
secretsdump.py 

### ISSUE THREAD

**Issue by wxz896446511** [fortra/impacket#1426]
from impacket.examples.secretsdump import LocalOperations, RemoteOperations, SAMHashes, LSASecrets, NTDSHashes, \
ImportError: cannot import name 'KeyListSecrets' from 'impacket.examples.secretsdump' (/usr/local/lib/python3.9/site-packages/impacket/examples/secretsdump.py)
<img width="982" alt="image" src="https://user-images.githubusercontent.com/43559734/195785310-c213a9ea-2d47-45d9-9bab-e75e96da5de7.png">

**Comment by 0xdeaddood** [comment]
Hi @wxz896446511!

That error means you have something wrong in your setup environment. It looks you're using a new version of secretsdump.py with an outdated installed library. Please update the Impacket library.

Closing. Reopen if you need further help.
