### ISSUE TITLE
secretsdump.py RemoteOperations failed: [Errno Connection error ("User":445)] [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by vicecityking** [fortra/impacket#1445]
### Configuration  
impacket version:  0.10.0
Python version:  3.9
Target OS:  Windows 10/11

### Debug Info

[+] Impacket Library Installation Path: C:\Users\migue\AppData\Local\Programs\Python\Python39\lib\site-packages\impacket[-] RemoteOperations failed: [Errno Connection error (miguel:445)] [Errno 11001] getaddrinfo failed
[+] Exiting NTDSHashes.dump() because No remote Operations available
[*] Cleaning up...

Hey, 
I have to use this program for an assignment. Im having trouble getting it to run. I keep getting the error in the title. My goal is to get the NTDS hash for my credentials. Ive tried it both on Windows 11 and Windows 10 VM but have had no luck.

RemoteOperations failed: [Errno Connection error ("User":445)] [Errno 11001] getaddrinfo failed

I would appreciate any help!

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
Space for additional context, investigative results, suspected issue.

**Comment by 0xdeaddood** [comment]
Hi @vicecityking
`[Errno 11001] getaddrinfo failed` indicates that the IP address of the host can't be resolved. Please check your DNS settings and verify that you are defining the correct target name.
