### ISSUE TITLE
SSL Routines, Internal error

### ISSUE THREAD

**Issue by 0xBinarySl3uth** [fortra/impacket#1453]
I am trying to use mssqlclient, after the OpenSSL has been updated it's not supporting legacy anymore, I think that's the reason that I have this issue. Has anyone a solution / workaround?

<img width="864" alt="Screenshot 2022-12-30 at 17 03 57" src="https://user-images.githubusercontent.com/121362809/210090753-78fd1896-33ac-4ce8-932b-b5b670008dd9.png">

**Comment by mubix** [comment]
This should be a pull request, not a closed issue.
