### ISSUE TITLE
Where is the service binary template used with *exec? 

### ISSUE THREAD

**Issue by albfflk** [fortra/impacket#1455]
Hello

Awesome job with impacket! 

The examples such as smbexec, wmiexec, etc upload a binary that will be started, I would like to customize it. Where can I find the source code (is it done in C?) of this service and use it with these examples? Any documentation, link or advise?

Happy new year

**Comment by SAERXCIT** [comment]
Hi,

Where do you see wmiexec.py and smbexec.py uploading a binary to the target? As far as I know, the only *exec that does that is psexec.py, which uploads RemCom (hardcoded there: https://github.com/fortra/impacket/blob/master/impacket/examples/remcomsvc.py. The upstream project is https://github.com/kavika13/RemCom).

smbexec.py creates and starts a service remotely using the service management RPCs (MS-SCMR), whose command line is basically the command we want to execute (https://github.com/fortra/impacket/blob/master/examples/smbexec.py#L272-L295). wmiexec.py starts a process remotely trough WMI (https://github.com/fortra/impacket/blob/master/examples/wmiexec.py#L287-L300).

**Comment by 0xdeaddood** [comment]
Thanks @SAERXCIT for the clarification! Closing.

@albfflk if you need further information, feel free to re-open this.
