### ISSUE TITLE
Shares Enumre

### ISSUE THREAD

**Issue by Brukusec** [fortra/impacket#1467]
Can someone help me. why do you see less shares with crackmapexec ? these additional shares are not hidden. this situation also happens with manspider, both use the impacket smb. also happens with all versions of impacket smbclient.py

![image](https://user-images.githubusercontent.com/11034605/213461784-0906eadf-ff61-4a44-97f4-f51cd983259e.png)

**Comment by AdrianVollmer** [comment]
Perhaps this: https://github.com/fortra/impacket/pull/947
