### ISSUE TITLE
DES is not defined

### ISSUE THREAD

**Issue by ghost** [fortra/impacket#1471]
### Configuration  
impacket version:  0.10.0
Python version:  3.9

### Debug Output With Command String  
python3 mssqlclient.py ARCHETYPE/sql_svc@10.129.186.254 -windows-auth                            ─╯
Impacket v0.10.1.dev1+20230120.195338.34229464 - Copyright 2022 Fortra

Password:
[*] Encryption required, switching to TLS
[-] name 'DES' is not defined

can someone please help me understand what the problem is here?

**Comment by 0xdeaddood** [comment]
Hi @Bxneyard 

Probably it's something related to your setup environment ([similar issue](https://github.com/fortra/impacket/issues/681)). Could you try reinstalling Impacket?

**Comment by 0xdeaddood** [comment]
No answer, closing. Please re-open if needed.
