### ISSUE TITLE
Kali6 Impacket-GetNPUsers fix

### ISSUE THREAD

**Issue by Dxaz** [fortra/impacket#1479]
### Configuration  
impacket version:  version: 0.10.1
Python version:  Python 3.10.9
Target OS:  Kali 2022.4 6.0.0-kali6-amd64

### Debug Output With Command String  
i.e.  
impacket-GetNPUsers  -h
```
Traceback (most recent call last):
  File "/usr/share/doc/python3-impacket/examples/GetNPUsers.py", line 47, in <module>
    from impacket.ldap import ldap, ldapasn1
  File "/home/kali/.local/lib/python3.10/site-packages/impacket/ldap/ldap.py", line 41, in <module>
    import OpenSSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3253, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
```

### Additional context  
Don't need help with fixing it I just want to address how I fixed it and why I think the error occurred to bring to the attention of whoever needs to know.

I got this error trying to run Impacket-GetNPUsers today. At first I figured it was my packages that were outdated or pip being outdated or even impacket being outdated as I haven't really used any of these things in over a few months on this machine.

So I went ahead and updated all my packges/repos/and got the latest version of impacket from github and from the kali repo using 

```
apt install impacket-scripts
```

however building it from scratch or using the repo package resulted in the same error.

So I decided to follow the traceback as I couldn't find any information on this and was getting really frustrated.

Looking at GetNPUsers.py line 47:
```
from impacket.ldap import ldap ldapasn1
```

It imports ldap which is the next part of the traceback that failed.
Viewing ldap.py line 41:

```
import OpenSSL
```

So on an so forth openssl imports another one and another one all the way until we get to crypto.py which fails at the function utils.deprecated()

```
utils.deprecated(
    load_pkcs12,
    __name__,
    (
        "PKCS#12 support in pyOpenSSL is deprecated. You should use the APIs "
        "in cryptography."
   ),
    DeprecationWarning,
    name="load_pkcs12",
)
```

Which is deprecation Warning and can effectively get commented out. which is what I did.

line 3253
```
#utils.deprecated(
#    load_pkcs12,
#    __name__,
#    (
#        "PKCS#12 support in pyOpenSSL is deprecated. You should use the APIs "
#        "in cryptography."
#   ),
#    DeprecationWarning,
#    name="load_pkcs12",
#)
```

and line 3352
```
#utils.deprecated(
#    load_pkcs12,
#    __name__,
#    (
#        "PKCS#12 support in pyOpenSSL is deprecated. You should use the APIs "
#        "in cryptography."
#   ),
#    DeprecationWarning,
#    name="load_pkcs12",
#)
```

This fixed the issue which is effectively an issue of crypto.py but because impacket uses ```import ldap``` it is affected. I suspect that all scripts that import ldap had this issue but I only wanted to use GetNPUsers today so I didn't test.

$ impacket-GetNPUsers -h
```
Impacket v0.10.1.dev1+20220720.103933.3c6713e3 - Copyright 2022 SecureAuth Corporation



usage: GetNPUsers.py [-h] [-request] [-outputfile OUTPUTFILE] [-format {hashcat,john}] [-usersfile USERSFILE] [-ts]

                     [-debug] [-hashes LMHASH:NTHASH] [-no-pass] [-k] [-aesKey hex key] [-dc-ip ip address]

                     target
....[snip].....


```

Hope this helps whoever runs into this issue in the future!

**Comment by anadrianmanrique** [comment]
related #1716

**Comment by mohnad-0b** [comment]
I have the same issue and I did this to solve it, and it worked for me

```bash
pip uninstall pyOpenSSL asgiref
sudo apt-get remove python3-asgiref 
pip install asgiref==3.7.2  
pip install pyOpenSSL==22.1.0 mitmproxy-rs==0.5.1 urwid-mitmproxy==2.1.1
pip install --upgrade impacke
```

**Comment by anadrianmanrique** [comment]
fixed now in mater branch. thanks
