### ISSUE TITLE
Error running psexec.py

### ISSUE THREAD

**Issue by 0xbara** [fortra/impacket#1482]
Hello everyone, I have this new issue when I run psexec.py. I've literally used a week ago, and now is not working

`❯ psexec.py
  File "/usr/local/bin/psexec.py", line 287
    promptRegex = rb'([a-zA-Z]:[\\\/])((([a-zA-Z0-9 -\.]*)[\\\/]?)+(([a-zA-Z0-9 -\.]+))?)?>$'
                                                                                            ^
SyntaxError: invalid syntax`

**Comment by 0xdeaddood** [comment]
Hi @0xbara!

The `SyntaxError` occurs because you are using `Python 2.X`. The regex expression detailed in the error is not supported in that version. Please take into account that we dropped support for Python 2 in our latest release.
