### ISSUE TITLE
review temp file creation in examples after https://github.com/fortra/impacket/pull/1486

### ISSUE THREAD

**Issue by anadrianmanrique** [fortra/impacket#1490]
In order to follow up https://github.com/fortra/impacket/pull/1486 we should review some missing changes related to temporal file creation in folders were regular users could potentially have access.
Files like .bat, bakup temporals and others should be taken into account (i.e. vss batch file in secretsdump)

**Comment by Sanmopre** [comment]
![Image](https://user-images.githubusercontent.com/40120264/222679133-472ae710-d816-40c6-b615-25a2be044ffd.jpg)

For the temporary file created when running secretsdump.py with the argument -use-vss, it has the correct file permissions.

**Comment by Sanmopre** [comment]
After testing smbexec temporary file, I found out that the _output file has the wrong file permission as shown in the image below.
![CaptureSMBEXEC](https://user-images.githubusercontent.com/40120264/231748762-5efe3dd2-4b8d-47e0-a6e8-4dde6c2fc88a.PNG)
