### ISSUE TITLE
[*] SMBD-Thread-7 (process_request_thread): Connection from MARVEL/FCASTLE@192.168.10.144 controlled, attacking target smb://192.168.10.254 [-] Authenticating against smb://192.168.10.254 as MARVEL/FCASTLE FAILED

### ISSUE THREAD

**Issue by ilyesmsk** [fortra/impacket#1494]
Could someone help me to fix this issue i don't know what is the problem the smb is off also the http is off
i did the scan and i got the adresss ip 
![5](https://user-images.githubusercontent.com/110234560/221824272-47bac661-02cc-41e5-b272-49d854a422c0.PNG)
![6](https://user-images.githubusercontent.com/110234560/221824308-9aac04fb-f311-4d67-974d-101fab77a752.PNG)
![7](https://user-images.githubusercontent.com/110234560/221824311-4a27b73e-847a-4ece-b8c1-aa27dba09774.PNG)
![8](https://user-images.githubusercontent.com/110234560/221824318-0140eec1-a7a3-4f9f-a185-437ee73985f9.PNG)
![1](https://user-images.githubusercontent.com/110234560/221824336-21a38252-3333-415e-9162-637d8dda4005.PNG)

![4](https://user-images.githubusercontent.com/110234560/221824227-dd84a523-1c67-482f-95db-16d3a087ea8e.PNG)
![2](https://user-images.githubusercontent.com/110234560/221824159-5016d180-2d7a-49f1-a76f-f7435b6a0223.PNG)
![3](https://user-images.githubusercontent.com/110234560/221824174-5025d8ae-c918-4d9f-ad96-13e94d96ba72.PNG)

**Comment by 0xdeaddood** [comment]
Hi @ilyesmsk

From what I can see, you're entering the wrong credentials when you try to access the remote server via File explorer. Pleas check that. Closing.

**Comment by ilyesmsk** [comment]
> 

Hi what i should do please help me

**Comment by noobhacker1** [comment]
hey i have the same issue, you found the solution yet?
thank you

**Comment by ilyesmsk** [comment]
No unfortunately

**Comment by mubix** [comment]
Windows 7 (I forget the exact timing) but that and above break accessing shares that allow guest access -> https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/guest-access-in-smb2-is-disabled-by-default

But if you give it FCASTLE's username and password that it's supposed to be it should work. That's what these flags are for:
```
  -username USERNAME    Username to authenticate clients
  -password PASSWORD    Password for the Username
```

**Comment by 0xmaximus** [comment]
> Could someone help me to fix this issue i don't know what is the problem the smb is off also the http is off i did the scan and i got the adresss ip ![5](https://user-images.githubusercontent.com/110234560/221824272-47bac661-02cc-41e5-b272-49d854a422c0.PNG) ![6](https://user-images.githubusercontent.com/110234560/221824308-9aac04fb-f311-4d67-974d-101fab77a752.PNG) ![7](https://user-images.githubusercontent.com/110234560/221824311-4a27b73e-847a-4ece-b8c1-aa27dba09774.PNG) ![8](https://user-images.githubusercontent.com/110234560/221824318-0140eec1-a7a3-4f9f-a185-437ee73985f9.PNG) ![1](https://user-images.githubusercontent.com/110234560/221824336-21a38252-3333-415e-9162-637d8dda4005.PNG)
> 
> ![4](https://user-images.githubusercontent.com/110234560/221824227-dd84a523-1c67-482f-95db-16d3a087ea8e.PNG) ![2](https://user-images.githubusercontent.com/110234560/221824159-5016d180-2d7a-49f1-a76f-f7435b6a0223.PNG) ![3](https://user-images.githubusercontent.com/110234560/221824174-5025d8ae-c918-4d9f-ad96-13e94d96ba72.PNG)

Maybe you're trying to relay a computer's credentials back to itself, which isn't possible due to security patches.
