### ISSUE TITLE
Impacket setup fails in latest version of Kali Linux

### ISSUE THREAD

**Issue by reybango** [fortra/impacket#1496]
### Configuration  
impacket version:  git pull from this repo as of 3/1/2023
Python version:  3.11.2
Target OS:  Linux kali 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux (This is the latest as of 3/1/2023)

### Explanation  
Since updating to the latest version of Kali Linux, the following error is thrown when running the Impacket setup program. This has been reported previously with no traction so I'm reposting to affirm that it is an issue: https://github.com/fortra/impacket/issues/1484

### Debug Output With Command String  
git pull
sudo python3 -m pip install .

``` error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

### Additional context  
This has been reported previously with no traction: https://github.com/fortra/impacket/issues/1484

**Comment by 0xdeaddood** [comment]
Hi @reybango!

Thanks for opening this issue. As you mentioned, Debian implemented new changes to prevent system-wide installations using pip. 

> If anybody is interesting in knowing more about that modification please check https://github.com/python/cpython/issues/102134 and https://peps.python.org/pep-0668/.

Regarding Impacket installation, we recommend using [virtual environments](https://docs.python.org/3/library/venv.html) to ensure you don't break the operating system.

If you need the examples to be available system-wide, we recommend using [pipx](https://pypa.github.io/pipx/).

- Install pipx on Linux distros: `sudo apt install pipx`
- Add /home/kali/.local/bin' is the PATH environment variable: `python3 -m pipx ensurepath`
- Grab impacket and from the directory run:  `python3 -m pipx install .`

I tested both options and I don't have any problems. If someone is experiencing problems with the installation following these options, please describe the issues here.

I'm going to keep this topic open until we'll update the Setup section in the README file.
