### ISSUE TITLE
smbserver.py: SMB2 not support????

### ISSUE THREAD

**Issue by fengyingkong** [fortra/impacket#1501]
![image](https://user-images.githubusercontent.com/32350484/224245857-6bedcc89-e49f-4263-b512-80405a3f782d.png)

I'm just a client initiating a request to query a file, but it keeps saying that SMB2 is not supported.

**Comment by 0xdeaddood** [comment]
Hi @fengyingkong!

Sorry for the late reply. That error means that the client does not support SMB2, so the server is fallbacking to SMB1. Then, the connection is established using that version. 

Closing
