### ISSUE TITLE
Which example is equivalent to winrs on Windows?

### ISSUE THREAD

**Issue by CaledoniaProject** [fortra/impacket#1557]
I'm looking for a winrs equivalent in impacket, I found "psexec, atexec, wmiexec, dcomexec", but no winrmexec.

Any ideas?

**Comment by 0xdeaddood** [comment]
Hi @CaledoniaProject!

There is no equivalent implementation of winrs in Impacket. You can check the tools mentioned in this [comment](https://github.com/fortra/impacket/issues/1403#issuecomment-1297298952) or maybe try with this [library](https://github.com/diyan/pywinrm). 

We re open for PRs if somebody is willing to implement it! Closing.

**Comment by CaledoniaProject** [comment]
Can't believe I created the same issue for another time.
