### ISSUE TITLE
dsinternals; I installed the module you mentioned, but I'm still experiencing the same problem. I'm not sure if the version is compatible. Does anyone know which version of this module is compatible with ntlmrelayx?

### ISSUE THREAD

**Issue by rodgarr** [fortra/impacket#1562]
ntlmrelayx.py
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[*] Protocol Client DCSYNC loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
Traceback (most recent call last):
  File "/home/rodgar/.local/bin/ntlmrelayx.py", line 384, in <module>
    from impacket.examples.ntlmrelayx.attacks import PROTOCOL_ATTACKS
  File "/home/rodgar/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/examples/ntlmrelayx/attacks/__init__.py", line 56, in <module>
    __import__(package + '.' + os.path.splitext(file)[0])
  File "/home/rodgar/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 43, in <module>
    from dsinternals.system.Guid import Guid
ModuleNotFoundError: No module named 'dsinternals'

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
I think it's related to #1320. Try to manually install it within your venv by using something like:
 `pip install dsinternals`

:sunflower:

**Comment by 0xdeaddood** [comment]
Hi @rodgarr

Please do what @ThePirateWhoSmellsOfSunflowers says.

Closing. Reopen if needed.

**Comment by jmeliendrez** [comment]
@rodgarr did you figure out a solution? I'm currently running into the same issue. Tried all the above.

**Comment by jmeliendrez** [comment]
Solved it. Impacket gets installed in the users home directory. You need to copy the dsinternals package from /usr/lib/python3/dist-packages into the /home/[user]/.local/pipx/venvs/impacket/lib/python3.11/site-packages/ directory for it to work.
