### ISSUE TITLE
Ntlmrelayx ADCS "error obtaining certificate"

### ISSUE THREAD

**Issue by kaleemshaik7867** [fortra/impacket#1563]
### Configuration  
impacket version: Impacket v0.10.1.dev1+20230413.195351.6328a9b7 
Python version:  3.11.2
Target OS:  Kali

### Debug Output With Command String  
`ntlmrelayx.py -t http://192.168.126.242/certsrv/certfnsh.asp  -smb2support --adcs --template DomainController -debug `

when I ran dfscoerce I am getting error obtaining certificate error in ntlmrelayx 
https://github.com/Wh04m1001/DFSCoerce

`python shadowcoerce.py -u userone -p "testpassword" -d testlab.com 192.168.126.242 192.168.126.150`

![image](https://github.com/fortra/impacket/assets/7692857/ecb3219e-3a89-4b5c-b3d2-977531b8fede)

**Comment by edermi** [comment]
Having the exactly same issue, `-debug` unfortunately doesn't provide any further information

**Comment by J0rdanis99** [comment]
Hi @kaleemshaik7867 and @edermi,

I thought I was facing the same issue; however, I found that in the environment I was in, the default `DomainController` template was disabled and a custom certificate template was in use, called something like `Example Domain Controller Authentication`.

I then also found that for `ntlmrelayx.py`, I could not specify `--template "Example Domain Controller Authentication"`, or it failed. I had to specify `--template Example+Domain+Controller+Authentication` for the whitespaces to register appropriately.

Is this applicable to either of your issues?

**Comment by kaleemshaik7867** [comment]
Hello @J0rdanis99 , 

Did it work for you when you specify ```--template Example+Domain+Controller+Authentication```

**Comment by kaleemshaik7867** [comment]
> Having the exactly same issue, `-debug` unfortunately doesn't provide any further information
> 
> edit:// Relaying the same machine to another template works, so this might be related to the `DomainController` template?

@edermi when worked were you able to capture DC hash?

**Comment by J0rdanis99** [comment]
> Hello @J0rdanis99 ,
> 
> Did it work for you when you specify `--template Example+Domain+Controller+Authentication`

Correct, it did. When watching the ADCS logs, I could see that it was ignoring the spaces when I initially used quotes. Once I switched to concatenation with plus symbols, it registered the spaces and the attack was fully successful.

**Comment by J0rdanis99** [comment]
> That's the template: ![image](https://user-images.githubusercontent.com/7430871/243602159-9b92d47f-8480-4c12-8ffb-a84dce16171f.png) It's enabled but enrollment rights are restricted to NT Authority - maybe that was the issue?
> 
> When relaying to an issuable template, recovering the NT hash from PKINIT was possible (if that's the question @kaleemshaik7867)

I think the enrolment rights are unusual there but I can confirm later. For your info too, I used the Coercer tool to target a DC for coercing auth, as my typical method of choice.

**Comment by edermi** [comment]
I also used coercer

**Comment by 0xdeaddood** [comment]
Hi all!

`error obtaining certificate` could mean that the certificate template doesn't exist or is not _vulnerable_*. Please verify both things before running `ntlmrelayx`.

_* Tools such as [Certipy](https://github.com/ly4k/Certipy) and [Certify](https://github.com/GhostPack/Certify) can be used to check if a certificate is vulnerable._

Closing. Re-open if needed.

**Comment by CX330Blake** [comment]
> Having the exactly same issue, `-debug` unfortunately doesn't provide any further information
> 
> edit:// Relaying the same machine to another template works, so this might be related to the `DomainController` template?

Same problem here, also with DomainController
