### ISSUE TITLE
bug 1390 still an issue

### ISSUE THREAD

**Issue by bmilliron67** [fortra/impacket#1565]
### Configuration  
impacket version:  0.10.1.dev1+20230524.180921.8b3f9eff
Python version:  3.11.2
Target OS:  kali linux latest

### Debug Output With Command String  
python3 ticketer.py -domain-sid S-1-5-21-XXXXXXXXXXXXXXXXXXXX -nthash xxxxxxxxxxxxxxxxxxxxxx -domain xxx -debug foobar
Impacket v0.10.1.dev1+20230524.180921.8b3f9eff - Copyright 2022 Fortra          
                                                                                
[+] Impacket Library Installation Path: /usr/local/lib/python3.11/dist-packages/
impacket-0.10.1.dev1+20230524.180921.8b3f9eff-py3.11.egg/impacket               
[*] Creating basic skeleton ticket and PAC Infos                                
[*] Customizing ticket for xxx/foobar                                       
[+] VALIDATION_INFO after making it gold                                        
VALIDATION_INFO 
CommonHeader:                    
    Version:                         1 
    Endianness:                      16  
    CommonHeaderLength:              8 
    Filler:                          3435973836 
PrivateHeader:                   
    ObjectBufferLength:              416  
    Filler:                          3435973836 
    ObjectBufferLength:              416                              [179/2147]    Filler:                          3435973836                                 Data:                                                                               LogonTime:                                                                          dwLowDateTime:                   1593339648                             
        dwHighDateTime:                  31037437                               
    LogoffTime:                                                                 
        dwLowDateTime:                   4294967295                             
        dwHighDateTime:                  2147483647                             
    KickOffTime:                                                                
        dwLowDateTime:                   4294967295                             
        dwHighDateTime:                  2147483647                             
    PasswordLastSet:                                                            
        dwLowDateTime:                   1593339648                             
        dwHighDateTime:                  31037437 
    PasswordCanChange:              
        dwLowDateTime:                   0 
        dwHighDateTime:                  0 
    PasswordMustChange:                
        dwLowDateTime:                   4294967295 
        dwHighDateTime:                  2147483647 
    EffectiveName:                   'foobar' 
    FullName:                        ''         
   EffectiveName:                   'foobar'                         [158/2147]    FullName:                        ''                                             LogonScript:                     ''                                             ProfilePath:                     ''                                             HomeDirectory:                   ''                                         
    HomeDirectoryDrive:              ''                                         
    LogonCount:                      500                                        
    BadPasswordCount:                0                                          
    UserId:                          500                                        
    PrimaryGroupId:                  513                                        
    GroupCount:                      5                                          
    GroupIds:                                                                   
        [                                                                       
                                                                                
            RelativeId:                      513  
            Attributes:                      7 ,
                                                                                
            RelativeId:                      512 
            Attributes:                      7 ,
                                                                                
            RelativeId:                      520    
            Attributes:                      7 ,
            RelativeId:                      518                      [135/2147]
            Attributes:                      7 ,
              
            RelativeId:                      519 
            Attributes:                      7 ,
        ] 
    UserFlags:                       0 
    UserSessionKey:                  
        Data:                            b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00' 
    LogonServer:                     ''  
    LogonDomainName:                 'xxx' 
    LogonDomainId:                   
        Revision:                        1 
        SubAuthorityCount:               4 
        IdentifierAuthority:             b'\x00\x00\x00\x00\x00\x05' 
        SubAuthority:                    
            [
                 21, 
                 728853176,
                 1525511802,
                 592522955,
            ] 
                 592522955,                                           [114/2147]
            ]                                                                   
    LMKey:                           b'\x00\x00\x00\x00\x00\x00\x00\x00' 
    UserAccountControl:              528         
    SubAuthStatus:                   0                                          
    LastSuccessfulILogon:           
        dwLowDateTime:                   0 
        dwHighDateTime:                  0 
    LastFailedILogon:                                                           
        dwLowDateTime:                   0 
        dwHighDateTime:                  0 
    FailedILogonCount:               0                                          
    Reserved3:                       0 
    SidCount:                        0                                          
    ExtraSids:                       NULL  
    ResourceGroupDomainSid:          NULL                            
    ResourceGroupCount:              0                                          
    ResourceGroupIds:                NULL 
                                        
[*]     PAC_LOGON_INFO     
[*]     PAC_CLIENT_INFO_TYPE
[*]     EncTicketPart      
[*]     EncAsRepPart
[*] Signing/Encrypting final ticket                                             
[*]     PAC_SERVER_CHECKSUM                                                     
[*]     PAC_PRIVSVR_CHECKSUM                                                    
[+] Customized EncTicketPart        
EncTicketPart:                                                                  
 flags=1356857344                                                               
 key=EncryptionKey:                                                             
  keytype=23                                                                    
  keyvalue=lxisuukpuNgsilVk                                                     
                                                                                
 crealm=xxx                      
 cname=PrincipalName:                                                           
  name-type=1                                                                   
  name-string=SequenceOf:                                                       
   foobar                                                                       
                                                                                
 transited=TransitedEncoding:           
  tr-type=0                             
  contents=                             
authtime=20230605223046Z                                                       
 starttime=20230605223046Z                                                      
 endtime=20330602223046Z                                                        
 renew-till=20330602223046Z                                                     
 authorization-data=AuthorizationData:
                                

python3 GetNPUsers.py -k -no-pass -debug -dc-ip x.x.x.x xxx/foobar
Impacket v0.10.1.dev1+20230524.180921.8b3f9eff - Copyright 2022 Fortra                                                                                          
[+] Impacket Library Installation Path: /usr/local/lib/python3.11/dist-packages/impacket-0.10.1.dev1+20230524.180921.8b3f9eff-py3.11.egg/impacket
[*] Getting machine hostname                                                    [+] Connecting to x.x.x.x, port 389, SSL False
[+] Using Kerberos Cache: foobar.ccache                                         [+] SPN LDAP/GE1@xxx not found in cache                                     [+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/xxx@xxx
[+] Using TGT from cache                                                        
[+] Trying to connect to KDC at x.x.x.x                                    [+] Server time (UTC): 2023-06-05 22:27:03                                    
[+] Exception:    
Traceback (most recent call last):                                                File "/home/foresitelabs/impacket/examples/GetNPUsers.py", line 456, in <modul
e>                                                                              
    executer.run()
  File "/home/foresitelabs/impacket/examples/GetNPUsers.py", line 247, in run
    ldapConnection.kerberosLogin(self.__username, self.__password, self.__domain
, self.__lmhash, self.__nthash,
 File "/home/foresitelabs/impacket/examples/GetNPUsers.py", line 247, i[0/1930]    ldapConnection.kerberosLogin(self.__username, self.__password, self.__domain
, self.__lmhash, self.__nthash,                                                   File "/usr/local/lib/python3.11/dist-packages/impacket-0.10.1.dev1+20230524.18
0921.8b3f9eff-py3.11.egg/impacket/ldap/ldap.py", line 184, in kerberosLogin         tgs, cipher, oldSessionKey, sessionKey = getKerberosTGS(serverName, domain, 
kdcHost, tgt, cipher,                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^                                                             File "/usr/local/lib/python3.11/dist-packages/impacket-0.10.1.dev1+20230524.180921.8b3f9eff-py3.11.egg/impacket/krb5/kerberosv5.py", line 438, in getKerberosT
GS                                                                              
    r = sendReceive(message, domain, kdcHost)                                   
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                     File "/usr/local/lib/python3.11/dist-packages/impacket-0.10.1.dev1+20230524.18
0921.8b3f9eff-py3.11.egg/impacket/krb5/kerberosv5.py", line 91, in sendReceive
    raise krbError                                                              impacket.krb5.kerberosv5.KerberosError: Kerberos SessionError: KDC_ERR_TGT_REVOK
ED(TGT has been revoked)                                                        
[-] Kerberos SessionError: KDC_ERR_TGT_REVOKED(TGT has been revoked)

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
bug 1390 regression

**Comment by 0xdeaddood** [comment]
Hi @bmilliron67!

If you are targeting a fully patched server, the `username` must exist in the domain and have a matching RID (you have to set it with the `user-id` option). Please check that.

Closing. Re-open if needed.
