### ISSUE TITLE
Unnecessary dependency on future

### ISSUE THREAD

**Issue by frenzymadness** [fortra/impacket#1584]
Hello. It seems to me that the dependency on future does not need to be there:

https://github.com/fortra/impacket/blob/fdbd25684fe528f9b6f910e7a5ef4b33ea96defa/setup.py#L71

I cannot find any usages of future lib in the project. My motivation to check it was that the future library is broken with Python 3.12 and will be more with 3.13.

**Comment by gabrielg5** [comment]
Closed in #1598
