### ISSUE TITLE
SSL routines', '', 'no protocols available'

### ISSUE THREAD

**Issue by 1oftheguthakrs** [fortra/impacket#1592]
### Configuration  
impacket version:  v0.10.0
Python version:  3.8.7
Target OS:  Kali Linux

### Debug Output With Command String  
``impacket-mssqlclient -port 1433 user@IP -windows-auth``

``` Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

Password:
[*] Encryption required, switching to TLS
[-] [('SSL routines', '', 'no protocols available')]
``` 

I want to report seeing this issue on v0.10.0, which is on the latest Kali right now. Once updated to the latest version it works fine.

Update to the latest version
`` pip install git+https://github.com/fortra/impacket.git``

**Comment by 1oftheguthakrs** [comment]
Already fixed. Just need to update to v0.11.0

**Comment by mfrey** [comment]
how did you solve this? there is no v0.11.0 release (yet).

**Comment by 1oftheguthakrs** [comment]
That's the stable release. 
Get v0.11.0 by running
``pip install git+https://github.com/fortra/impacket.git``
