### ISSUE TITLE
[Packaging] Restructure `examples`

### ISSUE THREAD

**Issue by cmahnke** [fortra/impacket#1597]
For me as an "end user developer" the most interesting code parts are currently part of [`examples`](https://github.com/fortra/impacket/tree/master/examples) directory. I would like to reuse this code as a python library, without adding the binary path to `sys.path`.

Given the example `wmiexec`.

Please consider using the code to the [example python package](https://github.com/fortra/impacket/tree/master/impacket/examples) to be able to use them directly
```python
from impacket.examples.wmiexec import *
```

The existing files would stay in `examples` but will import the required functionality from `impacket.examples` and only contain the command line handling (`argparse`). This way the command line tools will be kept and the provided (high level) functionality can be used like a library.

**Comment by 0xdeaddood** [comment]
Hi @cmahnke!

That's the spirit of the examples scripts. They are applied examples of the library. You can replicate anything from the scratch using the library.

**Comment by cmahnke** [comment]
Please reconsider this issue:
* The most valuable parts (at least for me) of this repository aren't part of the library
*  It's the purpose of a library to avoid replication / reimplementation
* There already is a package `examples`, so the spirit won't be altered
* This would be a second / high level API
