### ISSUE TITLE
DEPRECATION

### ISSUE THREAD

**Issue by sec13b** [fortra/impacket#1621]
any help, please 

Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/impacket-0.12.0.dev1+20230921.20754.9c8f344b-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..                                                                                            
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (23.2.1)        

┌──(kali㉿kali)-[~/Desktop]
└─$ pip3 install impacket
Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/impacket-0.12.0.dev1+20230921.20754.9c8f344b-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Requirement already satisfied: impacket in /usr/local/lib/python3.11/dist-packages/impacket-0.12.0.dev1+20230921.20754.9c8f344b-py3.11.egg (0.12.0.dev1+20230921.20754.9c8f344b)
Requirement already satisfied: charset_normalizer in /usr/lib/python3/dist-packages (from impacket) (3.2.0)
Requirement already satisfied: dsinternals in /usr/lib/python3/dist-packages (from impacket) (1.2.4)
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket) (2.2.5)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from impacket) (2.9.1)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket) (0.9.3)
Requirement already satisfied: pyOpenSSL>=21.0.0 in /usr/lib/python3/dist-packages (from impacket) (23.0.0)
Requirement already satisfied: pyasn1>=0.2.3 in /usr/lib/python3/dist-packages (from impacket) (0.4.8)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from impacket) (3.11.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from impacket) (68.1.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from impacket) (1.16.0)
                                                                                                                 
┌──(kali㉿kali)-[~/Desktop]

**Comment by SourCandy80** [comment]
Same issues!

Not just you. This is annoying.

**Comment by anadrianmanrique** [comment]
could you elaborate a bit ?

**Comment by SourCandy80** [comment]
Python 3.10. Using linux mint. This issue happens when trying to use linux
mint.

**Comment by stefan6419846** [comment]
Could you please elaborate on what your actual issue is? How did you generate the *impacket* egg distribution which is causing this warnings?
