### ISSUE TITLE
remove dsinternals dependency

### ISSUE THREAD

**Issue by anadrianmanrique** [fortra/impacket#1637]
As **_dsinternals_** projects it's currently GPL2 licensed we should remove dependencies with this project.
This will affect ldapattack.py in the context of ntlmrelayx.py

**Comment by anadrianmanrique** [comment]
linked to #1635

**Comment by anadrianmanrique** [comment]
**dsinternals** dependency was added in the context of #1297 and #1249

**Comment by p0dalirius** [comment]
Hey,

I am the creator of **pydsinternal** used in some scripts.

How did you remove the library? Didn't you just break the ShadowCredentials feature by doing this?

Best regards,

**Comment by ShutdownRepo** [comment]
> As **_dsinternals_** projects it's currently GPL2 licensed we should remove dependencies with this project.
> 
> This will affect ldapattack.py in the context of ntlmrelayx.py
> 
> 

@anadrianmanrique do you mind sharing the reasons the GPL2 license would be a problem in Impacket?
I don't understand the incompatibility here, and how it motivated the Impacket team to do a rewrite of the lib

Also, in my humble opinion, if the rewrite doesn't mention the original work & author, it makes the whole project look bad...

**Comment by stefan6419846** [comment]
> do you mind sharing the reasons the GPL2 license would be a problem in Impacket?

See my report at https://github.com/fortra/impacket/issues/1635#issue-1949065022. TL;DR: The FSF considers Apache-1.1 (the license of *impacket*) incompatible with the GPL. Thus IMHO there is no way to ship *impacket* in a compliant manner as long as *dsinternals* is a dependency.

**Comment by anadrianmanrique** [comment]
@p0dalirius thanks for reaching out. We updated shadow_credentials.py in https://github.com/fortra/impacket/commit/f9d1d74763e6694596aa69061b7ff20d4dc363c0 in order to reference your project. Apologies for not mentioning it in first place. Let me know if something else needs to be updated.
As @stefan6419846 pointed out, Apache1.1 is not compatible with GPL2, that's why we decided to remove that dependency.
If you consider eventually to change your project's license, let us know so we can revaluate to link again to **pydsinternals**.
Thanks, and apologies again for any inconvenience

**Comment by stefan6419846** [comment]
> Also, in my humble opinion, if the rewrite doesn't mention the original work & author, it makes the whole project look bad...

IANAL, but in theory this can be considered a violation of the GPL licensing terms - the GPL requires all derivatives to have the same license unless there is explicit written permission from all affected authors to re-license it, which should be documented accordingly. Apart from this, attribution like in https://github.com/fortra/impacket/commit/f9d1d74763e6694596aa69061b7ff20d4dc363c0 can be considered insufficient as well.

**Comment by ShutdownRepo** [comment]
Thank you @stefan6419846 and @anadrianmanrique for the prompt answers!
@p0dalirius, maybe you can initiate a license change by asking permissions to all pydsinternals contributors 🤷 maybe the GPL2 choice was not made with all those incompatibility issues in mind

**Comment by stefan6419846** [comment]
I think the main issue is with *impacket* being Apache-1.1, the GPL is just a limitation for cases where copyleft license pose an issue.

**Comment by gabrielg5** [comment]
Hi everyone!

yes Impacket can't use pydsinternals with its current licensing. Neither what we did is valid to be aligned with it.

Did the opposite way here as we should have talked with you @p0dalirius first, but we have 2 options now:
* wether you work with pydsinternals contributors to change its license to one Impacket could use or
* Impacket writes its own implementation of those needed classes

If you can confirm if first option is a possibility. Switching to the second if not.
Again, sorry for the wrong order of events in this matter

thanks all!

**Comment by anadrianmanrique** [comment]
shadow credentials has been reimplemented in the context #1780
closing this one
