### ISSUE TITLE
Question about ntlmrelayx

### ISSUE THREAD

**Issue by enj5oy** [fortra/impacket#1639]
How i can configure ntlmrelayx for relay users from specific domain?
For specific user it is work:
python3 ntlmrelayx.py -t contoso\\user@192.168.0.2 -smb2support -socks
But for domain not:
python3 ntlmrelayx.py -t contoso\\*@192.168.0.2 -smb2support -socks

**Comment by anadrianmanrique** [comment]
that feature is not supported, thanks
