### ISSUE TITLE
Different behavior -t ldap and -tf 

### ISSUE THREAD

**Issue by enj5oy** [fortra/impacket#1646]
### Configuration  
impacket version:  v0.12.0.dev1+20231103.113049.2d00fc6a
Python version:  Python 3.11.6
Target OS:  Windows Server 2016

192.168.0.3 is Domain Controller
file.txt:
ldap://192.168.0.3
When relay Domain Admin contoso\administrator with -t ldap://192.168.0.3 attack works. 
![2023-11-08_12-06](https://github.com/fortra/impacket/assets/143943083/13fb9e5f-e9e5-422b-a63d-d696d2c80c37)

When attack -tf file.txt attack not works.
![2023-11-08_12-08](https://github.com/fortra/impacket/assets/143943083/4a005564-9b72-480b-ae32-4c1159ce1e63)
![2023-11-08_12-08_1](https://github.com/fortra/impacket/assets/143943083/322e3f5c-9420-4b13-8333-0409ee29b794)

**Comment by anadrianmanrique** [comment]
related to https://github.com/fortra/impacket/issues/1694

**Comment by anadrianmanrique** [comment]
please recheck. this sould be fixed in https://github.com/fortra/impacket/issues/1694
reopen if needed
