### ISSUE TITLE
Is it safe to use Impacket library. 

### ISSUE THREAD

**Issue by Zorrom** [fortra/impacket#1663]
### Configuration  
impacket version:  0.9.21
Python version:  3.6.1
Target OS:  Windows Server

I read on the internet and saw few articles stating that this library is used for performing attacks. I'd like to know if I am vulnerable to attacks if this package is installed on my system.  Please correct me if I'm wrong and let me know if it is safe to use this library. Thank you

**Comment by fsacer** [comment]
It's almost impossible to prove the security of any software so how would you expect that from an open-source project? But generally, you should be fine using it, keep in mind that certain scripts do start services on TCP and UDP ports.

**Comment by anadrianmanrique** [comment]
as @fsacer pointed out, security of software cannot be guaranteed ( either open/closed /what ever source ).
Either way, what you should do to improve your security as a user, is to keep your software updated. 0.9.21 is a really old version of impacket, and some security issues has been resolved in intermediate versions.
**Thanks**
