### ISSUE TITLE
Clarify meaning of disclaimer in readme

### ISSUE THREAD

**Issue by FeldrinH** [fortra/impacket#1665]
A disclaimer in the readme of this repo states:
> The information in this repository is for research and educational purposes and not meant to be used in production environments and/or as part of commercial products.

However, a large part of this repo is not "information", but a Python library.
Is the "information" in this disclaimer referring to the example code, or is it referring to the core Impacket library as well?
If the library is also included under the disclaimer, then that should probably be clarified in the disclaimer.

**Comment by anadrianmanrique** [comment]
It is clear that the disclaimer refers to the **information** ( **documentation + code** ) in the **_impacket_** repository.
Thanks!
