### ISSUE TITLE
class Structure.__str__ use function getData, but getData's result type is bytes

### ISSUE THREAD

**Issue by Griklit** [fortra/impacket#1675]
Structure.\_\_str\_\_ use function getData, but getData's return type is bytes

file: [structure.py](https://github.com/fortra/impacket/tree/master/impacket/structure.py)
line 120 and line 174

**Comment by anadrianmanrique** [comment]
issue was still present as hexlify returns b'' . fixed in https://github.com/fortra/impacket/commit/4e0e3174552c07b26d06ef3842eb8f708844498d
