### ISSUE TITLE
impacket-smbserver won't run with error message SyntaxError: multiple exception types must be parenthesized

### ISSUE THREAD

**Issue by AzureVision1** [fortra/impacket#1709]
└─$ impacket-smbserver           
Traceback (most recent call last):
  File "/usr/share/doc/python3-impacket/examples/smbserver.py", line 22, in <module>
    from impacket import smbserver, version
  File "/home/kali/.local/lib/python3.10/site-packages/impacket/smbserver.py", line 147
    except Exception, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
                                                           
└─$ python --version
Python 3.10.5

Can i get some help on this? I can't seem to run impacket-smbserver due to the wrong python version? But both impacket and my default are using Python3. Any help would be appreciated

**Comment by anadrianmanrique** [comment]
which version of impacket you have? it doesn't look like the latest one
