### ISSUE TITLE
unsupported mechtype 'negoex - spnego extended negotiation security mechanism'

### ISSUE THREAD

**Issue by sehot** [fortra/impacket#1726]
Hi
why i'm getting this error ?

**Comment by gabrielg5** [comment]
Hi @sehot,

what are you trying to run when receiving that exception?

Check the [bug_report.md](https://github.com/fortra/impacket/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide the minimum information required to diagnose the issue

thank you

**Comment by anadrianmanrique** [comment]
no response. closing this one
