### ISSUE TITLE
NTDSHashes.__init__() got an unexpected keyword argument 'skipUser'

### ISSUE THREAD

**Issue by sunilink** [fortra/impacket#1751]
### Configuration  
impacket version:  0.11.0
Python version:  3.12
Target OS:  Windows

py secretsdump.py is.local/newadmin:!qaz2wsx3edc@192.168.1.77 -just-dc-ntlm -user-status

Impacket v0.11.0 - Copyright 2023 Fortra
[-] NTDSHashes.__init__() got an unexpected keyword argument 'skipUser'
[*] Cleaning up...

I tried reinstalling impacket, it doesn't work

**Comment by 7MinSec** [comment]
Same issue but when dumping SAM using a local admin account.

**Comment by androidteacher** [comment]
In the base impacket folder,
pip3 install .
Try again.
This worked for me.

**Comment by 7MinSec** [comment]
Ah thank you!  I had installed under the `sudo` user, so my fix was just to re-run the command as `sudo`, but I think your fix would've worked for me too.

**Comment by merinmathews** [comment]
Hi, I am facing the same issue with impacket version 0.12.0. 
Python version: 3.12
Target OS: Windows Server 2019.

└─# python secretsdump.py -just-dc WinServer2019.local/WinServer-DC\$@192.168.50.97

Impacket v0.12.0.dev1 - Copyright 2023 Fortra

Password:
[-] NTDSHashes.__init__() got an unexpected keyword argument 'skipUser'
[*] Cleaning up...
