### ISSUE TITLE
datetime.datetime.utcnow() is deprecated in impacket-GetNPUsers

### ISSUE THREAD

**Issue by CookieThump** [fortra/impacket#1827]
### Configuration  
**impacket version:** 
Impacket v0.12.0 - Copyright Fortra, LLC and its affiliated companies

**Python version:** 
Python 3.12.6

**Target OS:** 
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2024.3
Codename:       kali-rolling

### Issue
impacket-GetNPUsers uses datetime.datetime.utcnow() in GetNPUsers.py in line 165.
Any usage of datetime.datetime.utcnow() throws the following deprecation warning in Python 3.12

> DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).

related: https://github.com/dbt-labs/dbt-core/issues/9791

**Expected Behavior**
This shouldn't happen

**Steps To Reproduce**
Run impacket-GetNPUsers with Python 3.12

### Solution
Replace line 165 in impacket-GetNPUsers
```now = datetime.datetime.utcnow() + datetime.timedelta(days=1)```
with
```now = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None) + datetime.timedelta(days=1)```

**Comment by exploide** [comment]
There are further places in the code invoking deprecated functions.

#1695 fixes this if it ever gets merged.

**Comment by anadrianmanrique** [comment]
fixed in #1695, thanks

**Comment by sagisar1** [comment]
impacket-GetNPUsers domain.com -no-pass -dc-ip <the dc ip>
Impacket v0.12.0 - Copyright Fortra, LLC and its affiliated companies 

[*] Getting TGT for test
/usr/share/doc/python3-impacket/examples/GetNPUsers.py:165: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).

still happens, any solution?

python version: 3.13.2
OS: kali linux 2025.1

**Comment by exploide** [comment]
> still happens, any solution?

This is fixed on `master`. You can search `GetNPUsers.py` in this repository, it does no longer contain `utcnow()`. If you still see the warning, you are using on older version. Either your installation is outdated or Kali decided to not ship a development version. A stable version has not been tagged since.

**Comment by sagisar1** [comment]
@exploide thanks for the information, I guess in this case it's a kali's problem. it's not so urgent for me, i'll wait when they will publish the newer version
