### ISSUE TITLE
File should be regf

### ISSUE THREAD

**Issue by ALI502539** [fortra/impacket#1830]
Hi, I am having the same error:
Unpacked data doesn't match constant value ''\x00\x00\x04\x00'' should be ''regf''
 I have exported the sam and system files from regedit and also from cmd using both save and export commands then I brought the sam.reg and system.reg file to Kali desktop and used the following command:
impacket-secretsdump -sam sam.reg -system system.reg 
And then he gives me the same error can someone please help??

**Comment by anadrianmanrique** [comment]
you're trying to parse an exported registry text file with a binary hive parser, that's why you're getting a should be **_regf_** error.'

**Comment by anadrianmanrique** [comment]
closing this as invalid
#1840 adds the posiblity to parse .reg files in the context of secretsdump and winregistry.py
