### ISSUE TITLE
Issue with nmapAnswerMachine.py not responding

### ISSUE THREAD

**Issue by jaganshankar** [fortra/impacket#213]
Input values in the code,
MAC = "01:02:03:04:05:06"
IP  = "xx.xx.xx.xx"
IFACE = "eth0"
OPEN_TCP_PORTS = [80, 443]
OPEN_UDP_PORTS = [111]
UDP_CMD_PORT = 12345
nmapOSDB = '/usr/share/nmap/nmap-os-db'

Started the script,
nmapAnswerMachine.py -p xx.xx.xx.xx

Start nmap from a machine,
nmap -sS -sU -p T:80,443 -O --script snmp-sysdescr --privilege xx.xx.xx.xx

Starting Nmap 7.12 ( https://nmap.org ) at 2016-09-29 01:28 EDT
WARNING: UDP scan was requested, but no udp ports were specified.  Skipping this scan type.
Nmap scan report for xx.xx.xx.xx
Host is up (0.000023s latency).
PORT    STATE  SERVICE
80/tcp  closed http
443/tcp closed https
Too many fingerprints match this host to give specific OS details
Network Distance: 0 hops

OS detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 3.06 seconds

**Comment by jaganshankar** [comment]
Any Help ?

**Comment by anadrianmanrique** [comment]
closing this as nmapAnswerMachine.py is now deprecated
