### ISSUE TITLE
examples/nmapAnswerMachine.py missing uncrc32

### ISSUE THREAD

**Issue by xambroz** [fortra/impacket#403]
Hello,
the example script examples/nmapAnswerMachine.py is using uncrc32, which used to be part of impacket, but is not anymore.

Thank you 
Michal Ambroz

**Comment by xambroz** [comment]
I guess the uncrc32.py should go to impacket/examples/uncrc32.py and the import in nmapAnswerMachine.py schould change to:
from impacket.example import uncrc32

**Comment by asolino** [comment]
Hey @xambroz

Fair point.. Would you mind grabbing the old copy and issue a PR?

**Comment by xambroz** [comment]
I will do.

**Comment by xambroz** [comment]
ping

**Comment by anadrianmanrique** [comment]
nmapAnswerMachine.py example it's already deprecated.
Thanks
