### ISSUE TITLE
Impacket support for python 3+

### ISSUE THREAD

**Issue by garastog-cisco** [fortra/impacket#424]
Hi Team,

We want to use Impacket python module to invoke WMI queries from a Linux box.
We need to understand if Pyhon3 onwards support is available in Impacket.
I can see below 2 branches for Python3 in github:
https://github.com/CoreSecurity/impacket/tree/python36

https://github.com/CoreSecurity/impacket/tree/python3

Please let us know what’s the difference between the two and which one has support for latest python 3.x version.
Also is there any release available for python3 version support of impacket.

**Comment by asolino** [comment]
Hey @gauravrasto 

I regret to say impacket currently does not have support for Python3. 
The [python3 branch](https://github.com/CoreSecurity/impacket/tree/python3) was an initial attempt to port some parts of the library but I didn't put much effort and got lost in time. I'm actually removing it now.
The [python36 branch](https://github.com/CoreSecurity/impacket/tree/python36) just started just some days ago aiming at reviving this effort. It will go very slow but hopefully steady. I now have a better understanding of what to do. Pay attention to what happens there.
