### ISSUE TITLE
wmiexec -target-ip

### ISSUE THREAD

**Issue by gfugihu** [fortra/impacket#591]
Hi there! Big fan of your project.
I'm writing to you after reading [this](https://github.com/SecureAuthCorp/impacket/issues/72#issuecomment-117300677) thread, where a `-target-ip` option for `wmiexec.py` was discussed.
I also had some of the same problems the author mentioned, so as per your request, I'm opening an issue so you can address it and hopefully add this flag sometime :)
Thank you so much for your work!

**Comment by anadrianmanrique** [comment]
fixed in #1710.
Thanks
