### ISSUE TITLE
Library is GPLv3 incompatible

### ISSUE THREAD

**Issue by obilodeau** [fortra/impacket#609]
We would like to use this library in our GPLv3 project [PyRDP](https://github.com/GoSecure/pyrdp/) to experiment with NLA support.

However, the Apache License v1.1 is incompatible with GPL software: https://www.gnu.org/licenses/license-list.html#GPLIncompatibleLicenses

Would you consider upgrading your license to Apache v2 which is GPLv3 compatible or modify your license to say _Apache v1.1 or later_?

**Comment by obilodeau** [comment]
Anniversary friendly bump :balloon: :cake:

**Comment by anadrianmanrique** [comment]
@obilodeau just spoted this one. We can analize your request in case you are still interested.
Thanks

**Comment by anadrianmanrique** [comment]
no response. closing this one
please reopen if needed. Thanks
