### ISSUE TITLE
HTTPRelayServer: target consumed before authentication starts

### ISSUE THREAD

**Issue by Rcarnus** [fortra/impacket#904]
### Configuration  
impacket version:  Impacket v0.9.22.dev1+20200629.145357.5d4ad6cc
Python version:  Python 3.8.3
Target OS:  Kali Linux

### Debug Output With Command String   
ntlmrelayx.py -t ldaps://hl-dc01.hackinglabs.lan --delegate-access -debug
```
[...]

[*] Servers started, waiting for connections
[*] HTTPD: Received connection from 172.16.205.20, attacking target ldaps://hl-dc01.hackinglabs.lan
[*] HTTPD: Client requested path: [...]
[*] HTTPD: Received connection from 172.16.205.20, but there are no more targets left!
```

### PCAP  
I cannot provide a full pcap nor details about the HTTP client. But I can provide screenshots if needed.

### Additional context  
When trying to relay a connection coming over HTTP, if the client does not try to authenticate with NTLM upfront, ntlmrelayx asks for NTLM authentication back to the client (using a 401 Unauthaurized Response): 
```
            if (proxy and proxyAuthHeader is None) or (not proxy and autorizationHeader is None):
                self.do_AUTHHEAD(message = b'NTLM',proxy=proxy)
                pass
```
Then, depending on the client, the client may choose to continue with the same TCP connection or close the existing one and restart with a fresh one.
HTTPRelayServer consumes a new target every time a new instance is created. For this reason if the client closes the TCP stream before trying to authenticate, the consumed target is lost:
```
    class HTTPHandler(http.server.SimpleHTTPRequestHandler):
        def __init__(self,request, client_address, server):
                [...]

                if self.server.config.target is None:
                    # Reflection mode, defaults to SMB at the target, for now
                    self.server.config.target = TargetsProcessor(singleTarget='SMB://%s:445/' % client_address[0])
                self.target = self.server.config.target.getTarget()
                if self.target is None:
                    LOG.info("HTTPD: Received connection from %s, but there are no more targets left!" % client_address[0])
                    return
```
This can be an issue when trying to relay towards one specific host such as a domain controller over ldap.

I would suggest delaying the authentication to a later stage, for instance when a messageType == 1 is identified:
```
            if messageType == 1:
                if not self.do_ntlm_negotiate(token, proxy=proxy):
```

I can propose with a PR if you agree with this change.

**Comment by anadrianmanrique** [comment]
new flag --keep-relying integrated in https://github.com/fortra/impacket/pull/1741 should resolve this issue.
please reopen if needed
thanks
