### ISSUE TITLE
Get Domain, hostname via smb w/o credentials

### ISSUE THREAD

**Issue by HynekPetrak** [fortra/impacket#971]
Would you mind to move the initial session setup (just before the actual login happens) from smb.py and smb3.py login_extended() and login() respectively into a separate function, to be able to get ServerName, ServerDomain, ServerDNSDomainName and ServerOS* without a logon attempt (e.g. when not having credentials)?

**Comment by asolino** [comment]
Have you tried login in w/o credentials? Even if it fails it should be enough to get what you need. [Here's](https://github.com/SecureAuthCorp/impacket/blob/master/examples/GetUserSPNs.py#L102) and example of this approach.

**Comment by HynekPetrak** [comment]
Yeah, at the moment I'm doing like that. My concert it, this is a bit heavier by attempting the logon and it might get logged on the server site as a false logon attempt.

**Comment by maaaaz** [comment]
https://github.com/maaaaz/impacket/blob/master/examples/getOSandSMBproperties.py

**Comment by anadrianmanrique** [comment]
already implemented in DumpNTLMInfo.py
Thanks!
