### ISSUE TITLE
Not support IPV6

### ISSUE THREAD

**Issue by CptGuo** [fortra/impacket#997]
### Configuration  
impacket version:  latest
Python version:  2.7
Target OS:  Linumx mint 20

### It riase erro,when use ip v6 address
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno -9] Address family for hostname not supported

**Comment by anadrianmanrique** [comment]
This doesn't seem an issue related to impacket. Check your environment configuration in order to support ipv6.
Thanks
